language: android
jdk: oraclejdk7
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The SDK version used to compile your project
    - android-17

    # Specify system image,
    - sys-img-armeabi-v7a-android-19

    # Additional components
    - add-on
    - extra

# Emulator Management: Create, Start and Wait
before_script:
  # Make a fake sd card
  - mkdir sdcard
  - mksdcard -l jetpackSdCard 1024M sdcard/jetpacksdcard.img
  # Create the emulator
  - echo no | android create avd --force -n jetpack -t android-17 --abi armeabi-v7a
  # Start the emulator
  - emulator -avd jetpack -sdcard sdcard/jetpacksdcard.img -no-audio -no-window -gpu on -no-boot-anim -noskin &
  # Wait for the emulator to start
  - android-wait-for-emulator
  # Unlock the emulator
  - adb shell input keyevent 82 &
  - adb shell input keyevent 82 &
  # Download nightly
  - wget -O fennec.apk https://ftp.mozilla.org/pub/mozilla.org/mobile/nightly/latest-mozilla-central-android-api-11/fennec-40.0a1.multi.android-arm.apk
  # Install Nightly
  - adb install fennec.apk
  # Install dependencies
  - npm install
  - export JPM_FIREFOX_BINARY=fennec
  - export JPM_ADB_PATH=/usr/local/android-sdk/platform-tools/adb
